### ISSUE TITLE
Wrong path of titatoggle-1.2.6-min.css

### ISSUE THREAD

**Issue by Shraa** [WrenSecurity/wrensec-deps#5]
RUN set -x \
 && git clone --depth 1 https://github.com/WrenSecurity/wrensec-deps /usr/src/wrensec-deps \
 && cd /usr/src/wrensec-deps/ \
 && ./install_openidm_5.5.0_deps.sh \
 && echo "Done"

...
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install-file (default-cli) @ standalone-pom ---
[ERROR] The specified file '/usr/src/wrensec-deps/repo/org/forgerock/commons/ui/libs/xdate/1.2.6/titatoggle-1.2.6-min.css' not exists
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.602 s
[INFO] Finished at: 2017-08-28T15:11:15+00:00
[INFO] Final Memory: 7M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file (default-cli) on project standalone-pom: The specified file '/usr/src/wrensec-deps/repo/org/forgerock/commons/ui/libs/xdate/1.2.6/titatoggle-1.2.6-min.css' not exists -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
...

**Comment by siepkes** [comment]
@smolafilip There are multiple artifact entries in the 5.5.0 script like `titatoggle` which try to find artifacts in the directory of `xdate`. Obviously the script is not going to find the artifacts there and break. Is the 5.5.0 script still a work in progress?

**Comment by smolafilip** [comment]
I have fixed those commands as part of pull request #6. It was a mistake I made when creating the script.

**Comment by siepkes** [comment]
This was fixed in #6.
